-- band
insert into band (
    id                    ,
    overview              ,
    icon_id               ,
    introduction          ,
    leader_user_id        ,
    member1_user_id       ,
    member2_user_id       ,
    member3_user_id       ,
    member4_user_id       ,
    member5_user_id       ,
    member6_user_id       ,
    member7_user_id       ,
    member8_user_id       ,
    member9_user_id       ,
    status_id             ,
    activity_area         ,
    activity_direction_id ,
    activity_date         ,
    online_flg            ,
    youtube_url           ,
    soundcloud_url        ,
    band_url              ,
    genre                 ,
    rule_age              ,
    rule_sex              ,
    recruitment_part      ,
    create_date           
) VALUES (
    0                    ,
    'ベース募集（ジャムセッション）' ,
    0                    ,
    '東京西多摩在住のギター30代、ドラム40代の二人組です。'          ,
    0        ,
    0       ,
    1       ,
    2       ,
    3       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    0             ,
    '東京都新宿区'         ,
    '0' ,
    '土日祝'         ,
    0            ,
    'https://yotube.com/xxxx'           ,
    'https://soundcloud.com/xxxx'        ,
    'https://wix.com/cccc'              ,
    'ロック、パンク'                 ,
    '20-30'              ,
    '無'              ,
    'ベース'      ,
    '2020/09/10'           
);

insert into band (
    id                    ,
    overview              ,
    icon_id               ,
    introduction          ,
    leader_user_id        ,
    member1_user_id       ,
    member2_user_id       ,
    member3_user_id       ,
    member4_user_id       ,
    member5_user_id       ,
    member6_user_id       ,
    member7_user_id       ,
    member8_user_id       ,
    member9_user_id       ,
    status_id             ,
    activity_area         ,
    activity_direction_id ,
    activity_date         ,
    online_flg            ,
    youtube_url           ,
    soundcloud_url        ,
    band_url              ,
    genre                 ,
    rule_age              ,
    rule_sex              ,
    recruitment_part      ,
    create_date           
) VALUES (
    1                    ,
    'キーボード募集！！' ,
    0                    ,
    '記事を読んでいただいた皆さまありがとうございます！'          ,
    4        ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    1             ,
    '東京都新宿区'         ,
    '0' ,
    '土日祝'         ,
    1            ,
    'https://yotube.com/xxxx'           ,
    'https://soundcloud.com/xxxx'        ,
    'https://wix.com/cccc'              ,
    'ロック、パンク'                 ,
    '20-30'              ,
    '無'              ,
    'キーボード'      ,
    '2020/09/10'           
);
insert into band (
    id                    ,
    overview              ,
    icon_id               ,
    introduction          ,
    leader_user_id        ,
    member1_user_id       ,
    member2_user_id       ,
    member3_user_id       ,
    member4_user_id       ,
    member5_user_id       ,
    member6_user_id       ,
    member7_user_id       ,
    member8_user_id       ,
    member9_user_id       ,
    status_id             ,
    activity_area         ,
    activity_direction_id ,
    activity_date         ,
    online_flg            ,
    youtube_url           ,
    soundcloud_url        ,
    band_url              ,
    genre                 ,
    rule_age              ,
    rule_sex              ,
    recruitment_part      ,
    create_date           
) VALUES (
    2                    ,
    '女性GtVoさん募集' ,
    0                    ,
    'こちら新規コピーバンドで女性GtVoを募集しています'          ,
    5        ,
    6       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    0             ,
    '大阪府堺市'         ,
    '1' ,
    '平日'         ,
    0            ,
    'https://yotube.com/xxxx'           ,
    'https://soundcloud.com/xxxx'        ,
    'https://wix.com/cccc'              ,
    'ポップス , ロック , アニソン/ボカロ'                 ,
    '20-'              ,
    '女性'              ,
    'ボーカル、ギター'      ,
    '2020/09/12'           
);
insert into band (
    id                    ,
    overview              ,
    icon_id               ,
    introduction          ,
    leader_user_id        ,
    member1_user_id       ,
    member2_user_id       ,
    member3_user_id       ,
    member4_user_id       ,
    member5_user_id       ,
    member6_user_id       ,
    member7_user_id       ,
    member8_user_id       ,
    member9_user_id       ,
    status_id             ,
    activity_area         ,
    activity_direction_id ,
    activity_date         ,
    online_flg            ,
    youtube_url           ,
    soundcloud_url        ,
    band_url              ,
    genre                 ,
    rule_age              ,
    rule_sex              ,
    recruitment_part      ,
    create_date           
) VALUES (
    3                    ,
    '面白いこと' ,
    0                    ,
    'ベースが弾けて面白いことができればいいです。頭が興奮する状態でフィードバックあの状態。 スタジオでのあの感覚が欲しいです。'          ,
    7        ,
    8       ,
    9       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    null       ,
    0             ,
    '東京都新宿区'         ,
    '0' ,
    '土日祝'         ,
    0            ,
    'https://yotube.com/xxxx'           ,
    'https://soundcloud.com/xxxx'        ,
    'https://wix.com/cccc'              ,
    '無し'                 ,
    '-40'              ,
    '無し'              ,
    'ベース'      ,
    '2020/09/20'           
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    0                   ,
    'XXXXXXX'                 ,
    'まー'                   ,
    0              ,
    'ピアノ'                 ,
    '1'     ,
    'ポップス'           ,
    '10-feet、スピッツ'          ,
    '神奈川県横浜市'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    1                   ,
    'XXXXXXX'                 ,
    '腹'                   ,
    0              ,
    'コーラス'                 ,
    '1'     ,
    'アカペラ'           ,
    'バーバショップ'          ,
    '池袋'        ,
    '2',
    '無'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    2                   ,
    'XXXXXXX'                 ,
    '千尋'                   ,
    0              ,
    'ドラム'                 ,
    '1'     ,
    'ノージャンル'           ,
    '鬼束'          ,
    '小金井市'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    3                   ,
    'XXXXXXX'                 ,
    '太一'                   ,
    0              ,
    'ギター、コーラス、ボーカル'                 ,
    '1'     ,
    'アカペラ、合掌、アニソン'           ,
    ''          ,
    '神奈川県横浜市'        ,
    '1',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    4                   ,
    'XXXXXXX'                 ,
    'まーまー'                   ,
    1              ,
    'ギター'                 ,
    '1'     ,
    'クラシック'           ,
    'バッハ'          ,
    '愛媛県'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    5                   ,
    'XXXXXXX'                 ,
    'まー'                   ,
    0              ,
    'ピアノ'                 ,
    '1'     ,
    'ポップス'           ,
    '10-feet、スピッツ'          ,
    '神奈川県横浜市'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    6                   ,
    'XXXXXXX'                 ,
    'まー'                   ,
    0              ,
    'ピアノ'                 ,
    '1'     ,
    'ポップス'           ,
    '10-feet、スピッツ'          ,
    '神奈川県横浜市'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    7                   ,
    'XXXXXXX'                 ,
    'まー'                   ,
    0              ,
    'ピアノ'                 ,
    '1'     ,
    'ポップス'           ,
    '10-feet、スピッツ'          ,
    '神奈川県横浜市'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    8                  ,
    'XXXXXXX'                 ,
    'まー'                   ,
    0              ,
    'ピアノ'                 ,
    '1'     ,
    'ポップス'           ,
    '10-feet、スピッツ'          ,
    '神奈川県横浜市'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
);

insert into band_user (
    id                   ,
    pswd                 ,
    nm                   ,
    icon_id              ,
    part                 ,
    hope_to_join_flg     ,
    like_genre           ,
    like_artist          ,
    activity_area        ,
    activity_direction_id,
    activity_date        ,
    youtube_url          ,
    soundcloud_url       ,
    user_url             ,
    introduction         ,
    last_login_date      ,
    create_date          
) VALUES (
    9                   ,
    'XXXXXXX'                 ,
    'まー'                   ,
    0              ,
    'ピアノ'                 ,
    '1'     ,
    'ポップス'           ,
    '10-feet、スピッツ'          ,
    '神奈川県横浜市'        ,
    '2',
    '土日祝'        ,
    ''          ,
    ''       ,
    ''             ,
    'よろしくお願いします'         ,
    '2020/09/20 20:20'      ,
    '2020/09/10'          
)


insert into band_htj (
    band_id      ,
    htj_user_id  ,
    msg          ,
    create_date  
) VALUES (
    0      ,
    1  ,
    '加入希望'          ,
    '2020/09/20'  
);


insert into band_htj_msg (
    band_id         ,
    htj_user_id     ,
    msg_seq         ,
    sender_user_id  ,
    msg             ,
    create_date     
) VALUES (
    0         ,
    2     ,
    0         ,
    '0'  ,
    'こんにちは'             ,
    '2020/09/25'     
);


insert into band_msg (
    band_id        ,
    msg_seq        ,
    sender_user_id ,
    msg            ,
    create_date    
) VALUES (
    2        ,
    0        ,
    5 ,
    'いつ集まりましょうか'            ,
    '2020/09/30'    
);